# Generated by Django 4.0.4 on 2022-04-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educator_details',
            new_name='Educator',
        ),
    ]
