# Generated by Django 4.0.4 on 2022-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0002_rename_educator_details_educator'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='university',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
