# Generated by Django 4.0.4 on 2022-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0005_alter_educator_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='university',
            field=models.CharField(default='MSU', max_length=150),
        ),
    ]
