# Generated by Django 4.0.4 on 2022-04-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0006_alter_educator_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='university',
        ),
    ]
